{ config, lib, pkgs, helper, ... }:

{
  users.mutableUsers = false;

  users.users.wsain = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "mlocate" "docker" ];
    openssh.authorizedKeys.keys = helper.constants.sshAuthorizedKeys;
    # generated by `mkpasswd -m scrypt`
    hashedPassword = "$7$CU..../....aluH5BErsfgYcgd/H6vPR1$SxDqpmNtJwF6eLetjMfOH3nsBp8fk4CpiAkeFjgFH08";
  };

  users.users.root = {
    hashedPassword = "$7$CU..../....2DAObhN40BtdyVdHspG43.$6G1hyQ7Se0dQfM5v7t4NqrScCj5XQCcIjmGDXAFHQKD";
  };

  users.groups = {
    wsain = { };
    docker = { };
    container = { };
    mlocate = { };
  };

  home-manager.users.wsain = rec {
    imports = (helper.lib.scanNixRelativeRootPath "home/tui")
      ++ (helper.lib.scanNixRelativeRootPath "home/gui")
      ++ (helper.lib.relativeToRootFiles "home" ["packages.nix"])
      ++ [{ _module.args = { user = "wsain"; }; }];
    home.username = "wsain";
    home.homeDirectory = "/home/wsain";
    home.stateVersion = "24.05";
  };
}
